KEY_PLAYPAUSE    1    /usr/bin/playerctl --all-players play-pause & mpc toggle
KEY_STOPCD       1    /usr/bin/playerctl --all-players stop & mpc stop
KEY_NEXTSONG     1    /usr/bin/playerctl --all-players next & mpc next
KEY_PREVIOUSSONG 1    /usr/bin/playerctl --all-players previous & mpc prev

KEY_MUTE         1    /usr/bin/amixer sset Headphone toggle
KEY_VOLUMEUP     1    /usr/bin/busctl call org.mpris.MediaPlayer2.ShairportSync /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player SetVolume d 1.0
